[dell_servers]
# 대상 노드명 선언 (물리 하드웨어 세팅 단계에서는 제어 컴퓨터(localhost)에서 iDRAC으로 원격 명령을 날리므로 ansible_connection은 local로 설정)
idc-node-01 ansible_connection=local

[baremetal_hosts]
# OS 사후 설정을 위해 main_orchestrator의 add_host 모듈이 동적으로 호스트 IP를 추가할 빈 그룹
